### PR TITLE
Removed gcv/cf folder

### PR DESCRIPTION
**Pull request by melinath**
This folder doesn't actually seem to be used any more (except for one utility function). Removing it clarifies the code structure.

Ostensibly this is where the code to support `spec.match.gcp`-style policies lives; however, the relevant code just doesn't seem to actually be reachable.

### CODE REVIEW

**Comment by melinath** [comment]
@maxsmythe Not sure if you might happen to have specific knowledge about this or if there might be something I'm missing.

**Comment by melinath** [comment]
I've confirmed that `spec.match.gcp` doesn't do anything currently. The match seems to be treated as empty - i.e. matching everything.

**Comment by maxsmythe** [comment]
Unfortunately no specific knowledge on my end

**Review by g-awmalik — APPROVED** [review]
Doesn't look it's being used. Good to go!

**Pull request merged**
